- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/install-packages/apt-transport-https.yml
    - include: tasks/install-packages/apt-update.yml
    - include: tasks/install-packages/apt-upgrade.yml
