- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/upgrade.yml
    - include: tasks/repo/albert.yml
    - include: tasks/repo/chrome.yml
    - include: tasks/repo/elementary-plus.yml
    - include: tasks/repo/flatpak.yml
    - include: tasks/repo/hh-ultravorka.yml
    - include: tasks/repo/openjdk.yml
    - include: tasks/repo/plus.yml
    - include: tasks/repo/tlp.yml
    - include: tasks/repo/tweaks.yml
    - include: tasks/update.yml
    - include: tasks/apt-install.yml
    - include: tasks/tlp.yml
    - include: tasks/upgrade.yml
    - include: tasks/cleanup.yml