- hosts: localhost local element env
  become: true
  become_user: root

  tasks:
    - include: tasks/repo/typora.yml
    - include: tasks/update.yml
    - include: tasks/upgrade.yml
    - include: tasks/cleanup.yml
